//export const FETCH_FORECAST_REQUEST = 'FETCH_FORECAST_REQUEST';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_FAIL = 'FETCH_FORECAST_FAIL';

export const SAVE_TEMPUNIT_FAIL = 'SAVE_TEMPUNIT_FAIL';
export const SAVE_TEMPUNIT_SUCCESS = 'SAVE_TEMPUNIT_SUCCESS';